/**
 * Generated by @jsonpages/cli. Dev server API: /api/save-to-file, /api/upload-asset, /api/list-assets.
 */
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import path from 'path';
import fs from 'fs';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const ASSETS_IMAGES_DIR = path.resolve(__dirname, 'public', 'assets', 'images');
const DATA_CONFIG_DIR = path.resolve(__dirname, 'src', 'data', 'config');
const DATA_PAGES_DIR = path.resolve(__dirname, 'src', 'data', 'pages');
const IMAGE_EXT = new Set(['.jpg', '.jpeg', '.png', '.gif', '.webp', '.svg', '.avif']);
const IMAGE_MIMES = new Set([
  'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml', 'image/avif',
]);
const MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024; // 5MB

function safeFilename(original, mimeType) {
  const base = (original.replace(/\.[^.]+$/, '').replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 128)) || 'image';
  const ext = original.includes('.') ? path.extname(original).toLowerCase() : (mimeType?.startsWith('image/') ? `.${(mimeType.split('/')[1] || 'png').replace('jpeg', 'jpg')}` : '.png');
  return `${Date.now()}-${base}${IMAGE_EXT.has(ext) ? ext : '.png'}`;
}

function listImagesInDir(dir, urlPrefix) {
  const list = [];
  if (!fs.existsSync(dir)) return list;
  for (const name of fs.readdirSync(dir)) {
    if (IMAGE_EXT.has(path.extname(name).toLowerCase())) list.push({ id: name, url: `${urlPrefix}/${name}`, alt: name, tags: [] });
  }
  return list;
}

function sendJson(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

function sendJsonFile(res, filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' });
    res.end(content);
  } catch (e) {
    sendJson(res, 500, { error: e?.message || 'Read failed' });
  }
}

function isTenantPageJsonRequest(req, pathname) {
  if (req.method !== 'GET' || !pathname.endsWith('.json')) return false;
  const viteOrStaticPrefixes = ['/api/', '/assets/', '/src/', '/node_modules/', '/public/', '/@'];
  return !viteOrStaticPrefixes.some((prefix) => pathname.startsWith(prefix));
}

function normalizeManifestSlug(raw) {
  return decodeURIComponent(raw || '')
    .replace(/^\/+|\/+$/g, '')
    .replace(/\\/g, '/')
    .replace(/(\.schema)?\.json$/i, '');
}

async function loadWebMcpBuilders() {
  const moduleUrl = pathToFileURL(
    path.resolve(__dirname, '..', '..', 'packages', 'core', 'src', 'lib', 'webmcp-contracts.mjs')
  ).href;
  return import(moduleUrl);
}
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    {
      name: 'upload-asset-api',
      configureServer(server) {
        server.middlewares.use((req, res, next) => {
          const pathname = (req.url || '').split('?')[0];
          const isPageJsonRequest = isTenantPageJsonRequest(req, pathname);

          const handleManifestRequest = async () => {
            const { buildPageContract, buildPageManifest, buildSiteManifest } = await loadWebMcpBuilders();
            const ssrEntry = await server.ssrLoadModule('/src/entry-ssg.tsx');
            const buildState = ssrEntry.getWebMcpBuildState();

            if (req.method === 'GET' && pathname === '/mcp-manifest.json') {
              sendJson(res, 200, buildSiteManifest({
                pages: buildState.pages,
                schemas: buildState.schemas,
                siteConfig: buildState.siteConfig,
              }));
              return true;
            }

            const pageManifestMatch = pathname.match(/^\/mcp-manifests\/(.+)\.json$/i);
            if (pageManifestMatch && req.method === 'GET') {
              const slug = normalizeManifestSlug(pageManifestMatch[1]);
              const pageConfig = buildState.pages[slug];
              if (!pageConfig) {
                sendJson(res, 404, { error: 'Page manifest not found' });
                return true;
              }

              sendJson(res, 200, buildPageManifest({
                slug,
                pageConfig,
                schemas: buildState.schemas,
                siteConfig: buildState.siteConfig,
              }));
              return true;
            }

            const schemaMatch = pathname.match(/^\/schemas\/(.+)\.schema\.json$/i);
            if (!schemaMatch || req.method !== 'GET') return false;

            const slug = normalizeManifestSlug(schemaMatch[1]);
            const pageConfig = buildState.pages[slug];
            if (!pageConfig) {
              sendJson(res, 404, { error: 'Schema contract not found' });
              return true;
            }

            sendJson(res, 200, buildPageContract({
              slug,
              pageConfig,
              schemas: buildState.schemas,
              siteConfig: buildState.siteConfig,
            }));
            return true;
          };

          if (
            req.method === 'GET' &&
            (
              pathname === '/mcp-manifest.json'
              || /^\/mcp-manifests\/.+\.json$/i.test(pathname)
              || /^\/schemas\/.+\.schema\.json$/i.test(pathname)
            )
          ) {
            void handleManifestRequest()
              .then((handled) => {
                if (!handled) next();
              })
              .catch((error) => {
                sendJson(res, 500, { error: error?.message || 'Manifest generation failed' });
              });
            return;
          }

          if (isPageJsonRequest) {
            const normalizedPath = decodeURIComponent(pathname).replace(/\\/g, '/');
            const slug = normalizedPath.replace(/^\/+/, '').replace(/\.json$/i, '').replace(/^\/+|\/+$/g, '');
            const candidate = path.resolve(DATA_PAGES_DIR, `${slug}.json`);
            const isInsidePagesDir = candidate.startsWith(`${DATA_PAGES_DIR}${path.sep}`) || candidate === DATA_PAGES_DIR;
            if (!slug || !isInsidePagesDir || !fs.existsSync(candidate) || !fs.statSync(candidate).isFile()) {
              sendJson(res, 404, { error: 'Page JSON not found' });
              return;
            }
            sendJsonFile(res, candidate);
            return;
          }
          if (req.method === 'GET' && req.url === '/api/list-assets') {
            try { sendJson(res, 200, listImagesInDir(ASSETS_IMAGES_DIR, '/assets/images')); } catch (e) { sendJson(res, 500, { error: e?.message || 'List failed' }); }
            return;
          }
          if (req.method === 'POST' && pathname === '/api/save-to-file') {
            const chunks = [];
            req.on('data', (chunk) => chunks.push(chunk));
            req.on('end', () => {
              try {
                const raw = Buffer.concat(chunks).toString('utf8');
                if (!raw.trim()) { sendJson(res, 400, { error: 'Empty body' }); return; }
                const body = JSON.parse(raw);
                const { projectState, slug } = body;
                if (!projectState || typeof slug !== 'string') { sendJson(res, 400, { error: 'Missing projectState or slug' }); return; }
                if (!fs.existsSync(DATA_CONFIG_DIR)) fs.mkdirSync(DATA_CONFIG_DIR, { recursive: true });
                if (!fs.existsSync(DATA_PAGES_DIR)) fs.mkdirSync(DATA_PAGES_DIR, { recursive: true });
                if (projectState.site != null) fs.writeFileSync(path.join(DATA_CONFIG_DIR, 'site.json'), JSON.stringify(projectState.site, null, 2), 'utf8');
                if (projectState.theme != null) fs.writeFileSync(path.join(DATA_CONFIG_DIR, 'theme.json'), JSON.stringify(projectState.theme, null, 2), 'utf8');
                if (projectState.page != null) {
                  const safeSlug = (slug.replace(/[^a-zA-Z0-9-_]/g, '_') || 'page');
                  fs.writeFileSync(path.join(DATA_PAGES_DIR, `${safeSlug}.json`), JSON.stringify(projectState.page, null, 2), 'utf8');
                }
                sendJson(res, 200, { ok: true });
              } catch (e) { sendJson(res, 500, { error: e?.message || 'Save to file failed' }); }
            });
            req.on('error', () => sendJson(res, 500, { error: 'Request error' }));
            return;
          }
          if (req.method !== 'POST' || req.url !== '/api/upload-asset') return next();
          const chunks = [];
          req.on('data', (chunk) => chunks.push(chunk));
          req.on('end', () => {
            try {
              const body = JSON.parse(Buffer.concat(chunks).toString('utf8'));
              const { filename, mimeType, data } = body;
              if (!filename || typeof data !== 'string') { sendJson(res, 400, { error: 'Missing filename or data' }); return; }
              const buf = Buffer.from(data, 'base64');
              if (buf.length > MAX_FILE_SIZE_BYTES) { sendJson(res, 413, { error: 'File too large. Max 5MB.' }); return; }
              if (mimeType && !IMAGE_MIMES.has(mimeType)) { sendJson(res, 400, { error: 'Invalid file type' }); return; }
              const name = safeFilename(filename, mimeType);
              if (!fs.existsSync(ASSETS_IMAGES_DIR)) fs.mkdirSync(ASSETS_IMAGES_DIR, { recursive: true });
              fs.writeFileSync(path.join(ASSETS_IMAGES_DIR, name), buf);
              sendJson(res, 200, { url: `/assets/images/${name}` });
            } catch (e) { sendJson(res, 500, { error: e?.message || 'Upload failed' }); }
          });
          req.on('error', () => sendJson(res, 500, { error: 'Request error' }));
        });
      },
    },
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@olonjs/core': path.resolve(__dirname, '..', '..', 'packages', 'core', 'src', 'index.ts'),
      'next/link': path.resolve(__dirname, './src/shims/next-link.tsx'),
    },
  },
  server: {
    fs: {
      allow: [
        path.resolve(__dirname, '..', '..'),
      ],
    },
    watch: {
      usePolling: true,
      interval: 300,
    },
  },
});




